# Generated by Django 4.2 on 2025-01-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
